networks:
  medods:
    driver: bridge

services:
#  notification-service:
#    container_name: notification-service
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    image: notification-service
#    ports:
#      - "8080:8080"
#      - "2112:2112"
#    depends_on:
#      postgresClient:
#        condition: service_healthy
#    networks:
#      - medods

  postgres:
    image: postgres:17.5
    container_name: postgres
    env_file:
      - config/config.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medods