basePath: /
definitions:
  api.ErrorResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  api.GUIDResponse:
    properties:
      guid:
        type: string
    type: object
  api.OKResponse:
    properties:
      status:
        type: string
    type: object
  api.RefreshTokenRequest:
    properties:
      refresh_token:
        example: your_refresh_token
        type: string
    type: object
  api.RespWithTokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: Документация API Medods
  title: Medods API
  version: "1.0"
paths:
  /auth/guid:
    post:
      description: Извлекает GUID из access token и возвращает его
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GUIDResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить GUID пользователя
      tags:
      - User
  /auth/logout:
    post:
      description: Инвалидирует access и refresh токены
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Выход пользователя
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Проводит валидацию и выдает новую пару токенов
      parameters:
      - description: Refresh token запрос
        in: body
        name: RefreshTokenRequest
        required: true
        schema:
          $ref: '#/definitions/api.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RespWithTokens'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить токены
      tags:
      - Auth
  /auth/tokens:
    post:
      description: Генерирует access и refresh токены по GUID пользователя
      parameters:
      - description: GUID пользователя
        in: query
        name: guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RespWithTokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Создать токены
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
